CRITICAL - 2022-11-24 17:54:40 --> mysqli_connect(): (HY000/1045): Access denied for user 'fallenx1_jangra'@'localhost' (using password: YES)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli_connect(...', '/home/fallenxt/...', 8, Array)
#1 /home/fallenxt/public_html/fallenx/app/Controllers/conn.php(8): mysqli_connect('localhost', 'fallenx1_jangra', 'fallenx1_jangra', 'fallenx1_jangra')
#2 /home/fallenxt/public_html/fallenx/app/Controllers/Connect.php(13): include('/home/fallenxt/...')
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(801): App\Controllers\Connect->__construct()
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-24 17:54:44 --> mysqli_connect(): (HY000/1045): Access denied for user 'fallenx1_jangra'@'localhost' (using password: YES)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli_connect(...', '/home/fallenxt/...', 8, Array)
#1 /home/fallenxt/public_html/fallenx/app/Controllers/conn.php(8): mysqli_connect('localhost', 'fallenx1_jangra', 'fallenx1_jangra', 'fallenx1_jangra')
#2 /home/fallenxt/public_html/fallenx/app/Controllers/Connect.php(13): include('/home/fallenxt/...')
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(801): App\Controllers\Connect->__construct()
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-24 17:54:46 --> mysqli_connect(): (HY000/1045): Access denied for user 'fallenx1_jangra'@'localhost' (using password: YES)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli_connect(...', '/home/fallenxt/...', 8, Array)
#1 /home/fallenxt/public_html/fallenx/app/Controllers/conn.php(8): mysqli_connect('localhost', 'fallenx1_jangra', 'fallenx1_jangra', 'fallenx1_jangra')
#2 /home/fallenxt/public_html/fallenx/app/Controllers/Connect.php(13): include('/home/fallenxt/...')
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(801): App\Controllers\Connect->__construct()
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-24 17:54:54 --> mysqli_connect(): (HY000/1045): Access denied for user 'fallenx1_jangra'@'localhost' (using password: YES)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli_connect(...', '/home/fallenxt/...', 8, Array)
#1 /home/fallenxt/public_html/fallenx/app/Controllers/conn.php(8): mysqli_connect('localhost', 'fallenx1_jangra', 'fallenx1_jangra', 'fallenx1_jangra')
#2 /home/fallenxt/public_html/fallenx/app/Controllers/Connect.php(13): include('/home/fallenxt/...')
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(801): App\Controllers\Connect->__construct()
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-24 17:55:01 --> mysqli_connect(): (HY000/1045): Access denied for user 'fallenx1_jangra'@'localhost' (using password: YES)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli_connect(...', '/home/fallenxt/...', 8, Array)
#1 /home/fallenxt/public_html/fallenx/app/Controllers/conn.php(8): mysqli_connect('localhost', 'fallenx1_jangra', 'fallenx1_jangra', 'fallenx1_jangra')
#2 /home/fallenxt/public_html/fallenx/app/Controllers/Connect.php(13): include('/home/fallenxt/...')
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(801): App\Controllers\Connect->__construct()
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-24 17:55:17 --> mysqli_connect(): (HY000/1045): Access denied for user 'fallenx1_jangra'@'localhost' (using password: YES)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli_connect(...', '/home/fallenxt/...', 8, Array)
#1 /home/fallenxt/public_html/fallenx/app/Controllers/conn.php(8): mysqli_connect('localhost', 'fallenx1_jangra', 'fallenx1_jangra', 'fallenx1_jangra')
#2 /home/fallenxt/public_html/fallenx/app/Controllers/Connect.php(13): include('/home/fallenxt/...')
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(801): App\Controllers\Connect->__construct()
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-24 17:55:31 --> mysqli_connect(): (HY000/1045): Access denied for user 'fallenx1_jangra'@'localhost' (using password: YES)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli_connect(...', '/home/fallenxt/...', 8, Array)
#1 /home/fallenxt/public_html/fallenx/app/Controllers/conn.php(8): mysqli_connect('localhost', 'fallenx1_jangra', 'fallenx1_jangra', 'fallenx1_jangra')
#2 /home/fallenxt/public_html/fallenx/app/Controllers/Connect.php(13): include('/home/fallenxt/...')
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(801): App\Controllers\Connect->__construct()
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-11-24 17:56:09 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 17:56:09 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('RockyRock', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'RockyRock', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-24 17:56:30 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 17:56:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('RockyRock', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'RockyRock', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-24 17:58:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 17:58:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('rockynigam', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'rockynigam', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-24 17:58:28 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 17:58:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('rockynigam', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'rockynigam', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-24 17:58:42 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 17:58:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('RockyRock', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'RockyRock', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-24 17:58:59 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 17:58:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('rockynigam', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'rockynigam', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-24 17:59:11 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 17:59:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('rockynigam', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'rockynigam', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-24 17:59:16 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 17:59:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('RockyRock', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'RockyRock', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-24 18:00:46 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-11-24 18:00:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Rules.php(116): CodeIgniter\Database\BaseBuilder->get()
#3 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(277): CodeIgniter\Validation\Rules->is_not_unique('RockyRock', 'username', Array, NULL)
#4 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Validation/Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'RockyRock', Array, Array)
#5 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(77): CodeIgniter\Controller->validate(Array)
#7 /home/fallenxt/public_html/fallenx/app/Controllers/Auth.php(31): App\Controllers\Auth->login_action()
#8 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Auth->login()
#9 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 /home/fallenxt/public_html/fallenx/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/fallenxt/public_html/fallenx/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
